# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('krajina', models.CharField(max_length=250)),
                ('oblast', models.CharField(max_length=250)),
                ('rajon', models.CharField(max_length=250)),
                ('rozpl', models.IntegerField(default=0)),
                ('ploshch', models.IntegerField(default=0)),
                ('toppotype', models.CharField(max_length=30)),
                ('geomorform', models.CharField(max_length=250)),
                ('vysotnadrm', models.IntegerField(default=0)),
                ('chron', models.CharField(max_length=250)),
                ('nvchron', models.CharField(max_length=250)),
                ('data', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archapp.User'),
        ),
    ]
