# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 21:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('archapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 4, 25, 21, 34, 27, 316580, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
