# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='usedby',
            field=models.IntegerField(default=None),
        ),
    ]
