# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archapp', '0002_property_usedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='linked',
        ),
        migrations.RemoveField(
            model_name='property',
            name='usedby',
        ),
        migrations.AddField(
            model_name='filter',
            name='oftype',
            field=models.IntegerField(choices=[(1, 'Integer'), (2, 'Boolean'), (3, 'Double'), (4, 'String')], default=0, verbose_name='Value type'),
        ),
        migrations.AddField(
            model_name='filter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfilters', to='archapp.Filter'),
        ),
        migrations.AlterField(
            model_name='property',
            name='oftype',
            field=models.IntegerField(choices=[(1, 'Integer'), (2, 'Boolean'), (3, 'Double'), (4, 'String')], default=0, verbose_name='Value type'),
        ),
    ]
